# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

        # Exclude some solutions because black doesn't support pattern matching
        exclude: |
            (?x)^(
                aoc2021/day_02.py|
                aoc2021/day_16.py
            )$


    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
                "-rn", # Only display messages
                "-sn", # Don't display the score
            ]


    -   id: mypy
        name: mypy
        entry: mypy --show-traceback
        language: system
        types: [python]

        # Exclude some solutions because black doesn't support pattern matching
        exclude: |
            (?x)^(
                aoc2021/day_02.py|
                aoc2021/day_16.py
            )$

    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
